language: node_js

script:
  - DPRO=local ./node_modules/.bin/magellan --sauce_create_tunnels --external_build_id=$TRAVIS_BUILD_ID --profile all --tags pageobject --max_workers=${MAGELLAN_MAX_WORKERS} --sync_browsers safari:10

node_js:
  - v8
  - v7
  - v6
  - v5
  - 10

# Use container-based Travis infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  hosts:
    - dev.walmart.com

before_install:
  # ensure latest npm installed.
  - npm install -g npm
  - npm --version
  - export MAGELLAN_BUILD_NAME=${TRAVIS_JOB_ID}_${TRAVIS_JOB_NUMBER}
  - export MAGELLAN_BUILD_ID=`date +%s`
  - export SAUCE_CONNECT_VERSION=4.4.9
  - export MOCK_HOSTNAME=dev.walmart.com
  - export MAGELLAN_MAX_WORKERS=7
